[project]
name = "jay-bot"
version = "0.1.0"
description = "A personalized chatbot based on Jay's persona"
dependencies = [
    "flask",
    "requests",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
